- hosts: server
  become: true
  tasks:
    - name: Backup live caddyfile
      ansible.builtin.copy:
        src: /etc/caddy/Caddyfile
        dest: /etc/caddy/Caddyfile.live
        mode: preserve
    - name: Set maint caddyfile
      ansible.builtin.copy:
        src: /etc/caddy/Caddyfile.maint
        dest: /etc/caddy/Caddyfile
        mode: preserve
    - name: Reload caddy service
      ansible.builtin.service:
        name: caddy
        state: reloaded
