- hosts: server
  become: true
  tasks:
    - name: Start maintenance
      ansible.builtin.shell: |
        if [ -f /etc/caddy/Caddyfile.live ]; then
          mv /etc/caddy/Caddyfile.live /etc/caddy/Caddyfile
        fi
      args:
        executable: /bin/bash
    - name: Reload caddy service
      ansible.builtin.service:
        name: caddy
        state: reloaded
