- hosts: server
  become: true
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        pkg: [curl, ufw]
        state: present
        update_cache: true
    - name: Reset ufw settings
      ansible.builtin.shell: |
        ufw --force reset
        ufw default deny incoming
        ufw default allow outgoing
        ufw allow 22
        ufw allow 80
        ufw allow 443
        ufw --force enable
    - name: Enable ufw service
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true
    - name: Cleanup ufw backups
      ansible.builtin.shell: |
        rm /etc/ufw/after6.rules.* || true
        rm /etc/ufw/after.rules.* || true
        rm /etc/ufw/before6.rules.* || true
        rm /etc/ufw/before.rules.* || true
        rm /etc/ufw/user6.rules.* || true
        rm /etc/ufw/user.rules.* || true
