- hosts: server
  become: true
  tasks:
    - name: Install phpmyadmin
      ansible.builtin.apt:
        pkg:
          - phpmyadmin
          - php-fpm
          - php-mbstring
          - php-bcmath
          - php-xml
          - php-mysql
          - php-common
          - php-gd
          - php-cli
          - php-curl
          - php-zip
          - php-gd
    - name: Disable apache service
      ansible.builtin.service:
        name: apache2
        enabled: false
        state: stopped
    - name: reload caddy service
      ansible.builtin.service:
        name: caddy
        state: reloaded
