host: "0.0.0.0"
port: 8084

site_base_url_api: "http://www.clothingloop.localhost:8080/api"
site_base_url_fe: "http://www.clothingloop.localhost:8080"

cookie_domain: "clothingloop.localhost"
cookie_https_only: false

stripe_secret_key: "secret"
stripe_webhook: "secret"

jwt_secret: "secret"

db_host: "db"
db_port: 3306
db_name: "clothingloop"
db_user: "clothingloop"
db_pass: "72bd3937e91363a747f810e7"

smtp_host: "mailpit"
smtp_port: 1025
smtp_sender: "dev@example.com"
smtp_user: "dev@example.com"
smtp_pass: ""

goscope2_user: "admin"
goscope2_pass: "admin"

mattermost_url: "http://mattermost:8065"
# 1. Enable personal access tokens in System Console > Integrations > Integration Management.
# 2. Sign in to the admin user account to create a personal access token.
# 3. Go to Profile > Security > Personal Access Tokens, then select Create Token.
mattermost_token: "secret"
mattermost_smtp_host: "mattermost_mail"
mattermost_smtp_port: 2525
images_dir: "./images"
