[nl_NL]
[[App name]]
Mijn Clothing Loop

[[Short description]]
Mensen bekrachtigen kleding met anderen te ruilen.

[[Full description]]
De Clothing Loop is een initiatief waarmee mensen gemakkelijk kleding kunnen ruilen met anderen in hun eigen buurt.
Het is leuk, gratis en duurzaam!

Het idee is simpel: (grote) tassen gevuld met kleding​ reizen langs een route; langs alle deelnemers in een bepaalde stad of wijk.

[en_US]
[[App name]]
My Clothing Loop

[[Short description]]
Empowers people to swap clothes with others in their own neighborhood.

[[Full description]]
The Clothing Loop is an initiative that offers an easy way for people to swap clothes with others in their own neighborhood.
It’s fun, free and sustainable!

The idea is simple: (large) bags filled with clothes​ travel along a route past all participants in a certain city or district.