name: Deploy Acceptance
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies Frontend
        run: npm ci
        working-directory: ./frontend
      - name: Build public files
        run: npm run build:acceptance
        working-directory: ./frontend
      - name: Install SSH key
        uses: benoitchantre/setup-ssh-authentication-action@1.0.1
        with:
          private-key: ${{ secrets.VPS1_PRIVKEY }}
          known-hosts: ${{ secrets.VPS1_KNOWNHOSTS }}
      - name: Send public files to vps
        run: |
          ssh admin@vpsnode1.vps.webdock.cloud "mkdir -p /home/admin/cl-fe-acceptance"
          rsync -az --delete ./frontend/build/ admin@vpsnode1.vps.webdock.cloud:/home/admin/cl-fe-acceptance/
          ssh admin@vpsnode1.vps.webdock.cloud "\
          sudo rsync -z -rlt --chown=caddy:caddy --chmod=0775 --delete /home/admin/cl-fe-acceptance/ /var/caddy/acc.clothingloop.org/; \
          sudo systemctl reload caddy"
          echo "done"
